# Generated headers, generator tools and generated sources.
set(DG_GEN_DIR ${CMAKE_BINARY_DIR}/gen)
file(MAKE_DIRECTORY ${DG_GEN_DIR})

include(CheckTypeSize)
check_type_size(int DG_SIZEOF_INT LANGUAGE CXX)
math(EXPR DG_BITS_OF_INT "${DG_SIZEOF_INT} * 8")
math(EXPR DG_BITS_OF_PTR "${CMAKE_SIZEOF_VOID_P} * 8")
configure_file(${DG_ROOT}/cmake/ccenv.h.in ${DG_GEN_DIR}/ccenv.h @ONLY)

# bldsign.h carries the version, build date and a source hash
set(DG_VERSION ${PROJECT_VERSION})
string(TIMESTAMP DG_BUILD_DATE "%Y%m%d%H%M%S+0000" UTC)
file(GLOB_RECURSE _dg_hashed CONFIGURE_DEPENDS ${DG_ROOT}/src/*.cpp ${DG_ROOT}/src/*.h
     ${DG_ROOT}/include/*.h ${DG_ROOT}/rary/*.cpp)
list(SORT _dg_hashed)
set(_dg_md5s "")
foreach(f IN LISTS _dg_hashed)
  file(MD5 ${f} _m)
  string(APPEND _dg_md5s "${_m}\n")
endforeach()
string(MD5 _dg_all "${_dg_md5s}")
string(SUBSTRING "${_dg_all}" 0 16 DG_SRC_MD5)
configure_file(${DG_ROOT}/cmake/bldsign.h.in ${DG_GEN_DIR}/bldsign.h @ONLY)

# randtext.cpp is included by filters/sslway.cpp
string(TIMESTAMP _dg_epoch "%s" UTC)
math(EXPR _dg_ncase "${_dg_epoch} % 128")
set(_dg_rand "int randtext(int n){\n  switch(n){\n")
if(_dg_ncase GREATER 0)
  math(EXPR _dg_last "${_dg_ncase} - 1")
  foreach(i RANGE ${_dg_last})
    string(APPEND _dg_rand "    case ${i}: n++;\n")
  endforeach()
endif()
string(APPEND _dg_rand "  }\n  return n;\n}\n")
file(WRITE ${DG_GEN_DIR}/randtext.cpp "${_dg_rand}")

# Host tool that creates the dlopen stubs
add_executable(mkstab ${DG_ROOT}/filters/mkstab.cpp)
set_target_properties(mkstab PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/tools)

# Runs mkstab on a module source and exposes the stub as a generated source
function(dg_stub out_var module_c stub_name)
  set(stub ${DG_GEN_DIR}/stubs/${stub_name}.cpp)
  add_custom_command(OUTPUT ${stub}
    COMMAND ${CMAKE_COMMAND} -E make_directory ${DG_GEN_DIR}/stubs
    COMMAND ${CMAKE_COMMAND} -DTOOL=$<TARGET_FILE:mkstab> -DIN=${module_c} -DOUT=${stub}
            -P ${DG_ROOT}/cmake/RunTool.cmake
    DEPENDS mkstab ${module_c}
    COMMENT "Generating ${stub_name}.cpp"
    VERBATIM)
  set_source_files_properties(${stub} PROPERTIES GENERATED TRUE LANGUAGE CXX)
  set(${out_var} ${stub} PARENT_SCOPE)
endfunction()

# Embedded data files, generated by the embed host tool
function(dg_builtin out_var embed_target)
  set(out ${DG_GEN_DIR}/_builtin.cpp)
  file(GLOB_RECURSE data CONFIGURE_DEPENDS ${DG_ROOT}/src/builtin/*)
  set(patterns ../COPYRIGHT
    "builtin/**/*.gif" "builtin/**/*.ico" "builtin/**/*.bmp" "builtin/**/*.dll"
    "builtin/**/*.dhtml" "builtin/**/*.pem" "builtin/**/*.cnf" "builtin/**/*.cnv"
    "builtin/config/smtpgate/**/conf")
  list(JOIN patterns "|" joined)
  set(args "-IMPSIZE=${IMPSIZE}|${joined}")
  add_custom_command(OUTPUT ${out}
    COMMAND ${CMAKE_COMMAND} -DTOOL=$<TARGET_FILE:${embed_target}> "-DARGS=${args}"
            -DWORKDIR=${DG_ROOT}/src -DOUT=${out} -P ${DG_ROOT}/cmake/RunTool.cmake
    DEPENDS ${embed_target} ${data} ${DG_ROOT}/COPYRIGHT
    COMMENT "Generating _builtin.cpp"
    VERBATIM)
  set(${out_var} ${out} PARENT_SCOPE)
endfunction()
