# Source lists, one per legacy archive. File names are given without the .c suffix.

set(DG_SRCS_CORE
    version editconf admin notify shutter abort form2conf process vaddr conf svport ddi
    textconv script param env thmain syslog log svstat iotimeout misc msg yshell shio db
    hostlist cond service svconf filter master qstest delegate caps spinach stls tsp
    sudo gacl access ident dgauth dgsign ccache cache distrib bcounter ipno inets uns
    rident inetd thruwayd dget urlfind mount url gopher icp icap http httpx httplog
    httphead httpd cgi ssi htaccept htccx htswitch htmlgen htfilter nntp nntplist nntpgw
    enews pop smtp telnet ftp xferlog X wais whois xflash imap ldap smtpgate alias
    domain lpr sftp socks socks4 sox cuseeme coupler vsap tcprelay udprelay ftpgw
    filetype)

set(DG_SRCS_TELEPORT
    teleportd vehicle qzcode)

set(DG_SRCS_RESOLVY
    dnsnode resolv reshost rescache hostent resconf)

set(DG_SRCS_MIMEKIT
    mimeconv mimecodes mime pgp rfc822 mimehead mimeh_ovw str_codes gendom)

set(DG_SRCS_MD5
    md5c md5cb md5lib md5main)

set(DG_SRCS_FSX
    any2fdif)

set(DG_SRCS_GATES
    Gates_Win32)

# libpam_dl is generated by mkstab from rary/libpam.c
set(DG_SRCS_RARY
    SLL String ystring modfmt TLEX JIS codeconv pilsner str_stdio ccx html urlesc
    Strftime Timeofday strid hash bsort codec uu pstitle signal IsSolaris sched readycc
    fpoll fpolls frelay timer tar sed nbio vsaddr pelcgb credhy cksum asock lsock
    setutimes file fstat pam passwd syslog lock dglibs forkspawn Thread randstack
    rawcopy hostaddr socks5 cfilib netsh nonwin unix Finish)

# the *_dl stubs are generated by mkstab
set(DG_SRCS_CFI
    dl cfi cafe backup dping swft pdft)
set(DG_CFI_STUBS sslway gzip regex m17nccx)

# Compatibility functions linked into delegated and the helper programs
set(DG_SRCS_SUBST
    FMODE _-fcloseFILE2 _-fgetpos _-forkpty _-fseeko _-getrusage _-mkfifo _-mutex
    _-poll2 _-recv _-regex _-select _-setferror _-sgTTy _-statvfs __alloca __fchmod
    __fchown __flock __fork __gethostbyname2 __getrlimit __getwinsize __link __lstat
    __opendir __pthread_create __pthread_kill __ptrace __sigaction __symlink __sysinfo
    __syslog __tcsetattr __uname __usleep fpurge futimes malloc_size opt_s_caps
    opt_s_htaccept opt_s_pilsner opt_s_sox opt_s_stls opt_s_vsap p2i p2ll pam_start
    pendingcc sendFd1 setproctitle sigmask socklen_u spawnvp_ stdio strcasestr
    strrcasestr sysctl yp_match)

set(DG_SRCS_DELEGATED builtin delegated commands croncom remote)
