# Access control for an HTTP proxy
-P@PORT@
ADMIN=root@localhost
SERVER=http
# Accept clients from these hosts only
RELIABLE=@CLIENTS@
# Permit HTTP to any server
PERMIT="http:*:*"
# Reject one site
REJECT="http:*.blocked.example:*"
