# Log files in LOGDIR, with a protocol log in access log format
-P@PORT@
ADMIN=root@localhost
SERVER=http
LOGDIR=@LOGDIR@
LOGFILE=delegate.log
PROTOLOG=access.log
ERRORLOG=errors.log
MOUNT="/* http://@ORIGIN@/*"
